// Fotos reais: autoria, licenças e enquadramentos em IMG/paisagens/CREDITOS.md.
// Para ativar cada botão no futuro, preencha apenas href com o endereço da página.
window.AfloraPaisagensDados = [
  {
    "id": "lencois-maranhenses",
    "nome": "Lençóis Maranhenses",
    "regiao": "Maranhão · Nordeste",
    "descricao": "Dunas brancas e lagoas de chuva desenham uma paisagem que muda com as estações.",
    "imagem": "IMG/paisagens/lencois-maranhenses.webp",
    "alt": "Dunas claras entre lagoas verdes e azuis nos Lençóis Maranhenses.",
    "href": "",
    "credito": "Julius Dadalti",
    "fonte": "https://commons.wikimedia.org/wiki/File:Len%C3%A7%C3%B3is_Maranhenses_2018.jpg",
    "licenca": "CC BY-SA 4.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  {
    "id": "serra-dos-orgaos",
    "nome": "Serra dos Órgãos",
    "regiao": "Rio de Janeiro · Sudeste",
    "descricao": "Picos de pedra atravessam a névoa em um dos cenários mais marcantes da Mata Atlântica.",
    "imagem": "IMG/paisagens/serra-dos-orgaos.webp",
    "alt": "Raios do amanhecer entre os picos da Serra dos Órgãos, vistos dos Portais de Hércules.",
    "href": "",
    "credito": "Carlos Perez Couto",
    "fonte": "https://commons.wikimedia.org/wiki/File:Amanhecer_no_Hercules_--.jpg",
    "licenca": "CC BY-SA 3.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  {
    "id": "jalapao",
    "nome": "Jalapão",
    "regiao": "Tocantins · Norte",
    "descricao": "Entre o verde do cerrado, os fervedouros revelam nascentes de água cristalina.",
    "imagem": "IMG/paisagens/jalapao.webp",
    "alt": "Vista de cima de um fervedouro de água clara cercado pela vegetação do Jalapão.",
    "href": "",
    "credito": "Cléber Vinicius Demori",
    "fonte": "https://commons.wikimedia.org/wiki/File:Fervedouro_Parque_Jalap%C3%A3o_02.jpg",
    "licenca": "CC BY-SA 4.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  {
    "id": "fernando-de-noronha",
    "nome": "Fernando de Noronha",
    "regiao": "Pernambuco · Nordeste",
    "descricao": "O mar turquesa encontra as rochas dos Dois Irmãos neste arquipélago do Atlântico.",
    "imagem": "IMG/paisagens/fernando-de-noronha.webp",
    "alt": "Os dois rochedos do Morro Dois Irmãos diante do mar azul de Fernando de Noronha.",
    "href": "",
    "credito": "CCINTRA",
    "fonte": "https://commons.wikimedia.org/wiki/File:Fernando_de_Noronha_-_PE_-_Dois_Irm%C3%A3os.jpg",
    "licenca": "CC BY-SA 3.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  {
    "id": "cataratas-do-iguacu",
    "nome": "Cataratas do Iguaçu",
    "regiao": "Paraná · Sul",
    "descricao": "A força das quedas encontra a floresta, entre nuvens de água e horizontes verdes.",
    "imagem": "IMG/paisagens/cataratas-do-iguacu.webp",
    "alt": "Quedas das Cataratas do Iguaçu vistas de cima, com névoa de água sobre o cânion.",
    "href": "",
    "credito": "Mayra Villas Boas Francisco Zamulko",
    "fonte": "https://commons.wikimedia.org/wiki/File:Cataratas_do_Igua%C3%A7u_-_Vista_de_cima.jpg",
    "licenca": "CC BY-SA 4.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  {
    "id": "chapada-diamantina",
    "nome": "Chapada Diamantina",
    "regiao": "Bahia · Nordeste",
    "descricao": "O Morrão se ergue entre campos e vales, revelando a escala da paisagem baiana.",
    "imagem": "IMG/paisagens/chapada-diamantina.webp",
    "alt": "Morrão iluminado pelo sol sobre os campos da Chapada Diamantina.",
    "href": "",
    "credito": "Jeilsonandrade / Julian Herzog",
    "fonte": "https://commons.wikimedia.org/wiki/File:Morr%C3%A3o,_no_Parque_Nacional_da_Chapada_Diamantina_-_Bahia_crop_2.jpg",
    "licenca": "CC BY-SA 3.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  {
    "id": "gruta-do-lago-azul",
    "nome": "Gruta do Lago Azul",
    "regiao": "Bonito · Mato Grosso do Sul",
    "descricao": "Sob a rocha, um lago de azul profundo transforma a caverna em um mundo à parte.",
    "imagem": "IMG/paisagens/gruta-do-lago-azul.webp",
    "alt": "Lago azul intenso sob o teto de pedra da Gruta do Lago Azul, em Bonito.",
    "href": "#",
    "credito": "Sidney Michaluate",
    "fonte": "https://commons.wikimedia.org/wiki/File:Gruta_do_Lago_Azul_-_Bonito,_MS.JPG",
    "licenca": "CC BY-SA 4.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  {
    "id": "cachoeira-santa-barbara",
    "nome": "Cachoeira Santa Bárbara",
    "regiao": "Cavalcante · Goiás",
    "descricao": "Uma queda entre rochas e mata desemboca em um poço de água azul-esverdeada.",
    "imagem": "IMG/paisagens/cachoeira-santa-barbara.webp",
    "alt": "Cachoeira Santa Bárbara desaguando em um poço azul-esverdeado cercado de mata.",
    "href": "",
    "credito": "Renatoto",
    "fonte": "https://commons.wikimedia.org/wiki/File:Cachoeira_Santa_B%C3%A1rbara_-_Cavalcante_-_GO.jpg",
    "licenca": "CC BY-SA 4.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  {
    "id": "anavilhanas",
    "nome": "Anavilhanas",
    "regiao": "Amazonas · Norte",
    "descricao": "Ilhas de floresta e braços do Rio Negro desenham caminhos no coração da Amazônia.",
    "imagem": "IMG/paisagens/anavilhanas.webp",
    "alt": "Vista aérea das ilhas cobertas de floresta e dos canais do arquipélago de Anavilhanas.",
    "href": "",
    "credito": "Jason Auch from Calgary, Canada",
    "fonte": "https://commons.wikimedia.org/wiki/File:Anavilhanas2.jpg",
    "licenca": "CC BY 2.0",
    "licencaUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  {
    "id": "pantanal",
    "nome": "Pantanal",
    "regiao": "Mato Grosso · Centro-Oeste",
    "descricao": "Rios e vegetação compõem uma paisagem viva, conduzida pelo ritmo das águas.",
    "imagem": "IMG/paisagens/pantanal.webp",
    "alt": "Rio entre árvores floridas e vegetação no Parque Nacional do Pantanal Matogrossense.",
    "href": "",
    "credito": "Giovanna Colombi",
    "fonte": "https://commons.wikimedia.org/wiki/File:River_in_the_Parque_Nacional_do_Pantanal_Matogrossense_-_Caminho_do_rio.jpg",
    "licenca": "CC BY-SA 4.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  {
    "id": "cristo-redentor",
    "nome": "Cristo Redentor",
    "regiao": "Rio de Janeiro · Sudeste",
    "descricao": "No alto do Corcovado, a cidade e a floresta se encontram aos pés do monumento.",
    "imagem": "IMG/paisagens/cristo-redentor.webp",
    "alt": "Vista aérea do Cristo Redentor e do mirante no alto do Corcovado.",
    "href": "",
    "credito": "Gustavo Facci from Argentina",
    "fonte": "https://commons.wikimedia.org/wiki/File:Aerial_view_of_the_Statue_of_Christ_the_Redeemer.jpg",
    "licenca": "CC BY-SA 2.0",
    "licencaUrl": "https://creativecommons.org/licenses/by-sa/2.0"
  },
  {
    "id": "jericoacoara",
    "nome": "Jericoacoara",
    "regiao": "Ceará · Nordeste",
    "descricao": "Na Pedra Furada, o mar encontra uma abertura esculpida na rocha pelo tempo.",
    "imagem": "IMG/paisagens/jericoacoara.webp",
    "alt": "O arco natural da Pedra Furada à beira do mar em Jericoacoara.",
    "href": "",
    "credito": "Rosanetur from Rio de Janeiro, Brazil",
    "fonte": "https://commons.wikimedia.org/wiki/File:Pedra_Furada_de_Jericoacoara_-_Cear%C3%A1.jpg",
    "licenca": "CC BY 2.0",
    "licencaUrl": "https://creativecommons.org/licenses/by/2.0"
  }
];
